{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.compose.compiler",
    "module": "compiler",
    "version": "1.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "compiler-1.3.3.jar",
          "url": "compiler-1.3.3.jar",
          "size": 969786,
          "sha512": "bc97e1e460a028662cdd567736ce53a102d4638a7162a8793bc94794e6d68eb92f6ecd9ec386ab1cecad492d478cf69ed07815cad7424b494d4d40bfb9542450",
          "sha256": "d3547c70e5a8c6e7d12d540dc15902ea6fa9b7c841f58044ed11e3d55944e640",
          "sha1": "f550c7ef5f0ae5dde69c97bcf9a8f343ddf200b5",
          "md5": "8a29cea875d9cff1aaad00ee20141674"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compiler-1.3.3.jar",
          "url": "compiler-1.3.3.jar",
          "size": 969786,
          "sha512": "bc97e1e460a028662cdd567736ce53a102d4638a7162a8793bc94794e6d68eb92f6ecd9ec386ab1cecad492d478cf69ed07815cad7424b494d4d40bfb9542450",
          "sha256": "d3547c70e5a8c6e7d12d540dc15902ea6fa9b7c841f58044ed11e3d55944e640",
          "sha1": "f550c7ef5f0ae5dde69c97bcf9a8f343ddf200b5",
          "md5": "8a29cea875d9cff1aaad00ee20141674"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compiler-1.3.3-sources.jar",
          "url": "compiler-1.3.3-sources.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}