{
  "formatVersion": "1.1",
  "component": {
    "url": "../../skiko/0.7.36-edit/skiko-0.7.36-edit.module",
    "group": "org.jetbrains.skiko",
    "module": "skiko",
    "version": "0.7.36-edit",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "awtApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "skiko-awt-0.7.36-edit.jar",
          "url": "skiko-awt-0.7.36-edit.jar",
          "size": 1141274,
          "sha512": "a79559639220beb8f9647600aeeabc2feee5e09c0748ca004a89a529dfd6eb3714f4d645d1020fb6c43399428279abc1037cc2bfbb27042deb7a2a3ca3741b15",
          "sha256": "219446ded2dd35fe301d39c92c0f847472bfecab80546ffe0e57e79904d59488",
          "sha1": "c81147d225e4138c504772112fe48437a6693a05",
          "md5": "1d16bcdc336bd33a0f2228774773b63b"
        }
      ]
    },
    {
      "name": "awtRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "skiko-awt-0.7.36-edit.jar",
          "url": "skiko-awt-0.7.36-edit.jar",
          "size": 1141274,
          "sha512": "a79559639220beb8f9647600aeeabc2feee5e09c0748ca004a89a529dfd6eb3714f4d645d1020fb6c43399428279abc1037cc2bfbb27042deb7a2a3ca3741b15",
          "sha256": "219446ded2dd35fe301d39c92c0f847472bfecab80546ffe0e57e79904d59488",
          "sha1": "c81147d225e4138c504772112fe48437a6693a05",
          "md5": "1d16bcdc336bd33a0f2228774773b63b"
        }
      ]
    }
  ]
}
