{
  "formatVersion": "1.1",
  "component": {
    "url": "../../skiko/0.7.36-edit/skiko-0.7.36-edit.module",
    "group": "org.jetbrains.skiko",
    "module": "skiko",
    "version": "0.7.36-edit",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "awtApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "skiko-awt-0.7.36-edit.jar",
          "url": "skiko-awt-0.7.36-edit.jar",
          "size": 1140800,
          "sha512": "f570384d4f7bdc0a0f3b25dbfd6946b6ebce7f1ce79f93fe90fea6dac3424f9b41352fb61d40bf75349401343556ad86f8c90507ed1b7b0b536ba1b58a648c46",
          "sha256": "49c781b853def8f896b33fed47010b5b5656756752ca232fc8fb1a433083a0b8",
          "sha1": "a40debaaac45a99a14d0c8ed95f65dce85afcf45",
          "md5": "14c2f1f85558815965a6b1e656977f0a"
        }
      ]
    },
    {
      "name": "awtRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.5.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-jvm",
          "version": {
            "requires": "1.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "skiko-awt-0.7.36-edit.jar",
          "url": "skiko-awt-0.7.36-edit.jar",
          "size": 1140800,
          "sha512": "f570384d4f7bdc0a0f3b25dbfd6946b6ebce7f1ce79f93fe90fea6dac3424f9b41352fb61d40bf75349401343556ad86f8c90507ed1b7b0b536ba1b58a648c46",
          "sha256": "49c781b853def8f896b33fed47010b5b5656756752ca232fc8fb1a433083a0b8",
          "sha1": "a40debaaac45a99a14d0c8ed95f65dce85afcf45",
          "md5": "14c2f1f85558815965a6b1e656977f0a"
        }
      ]
    }
  ]
}
