{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.skiko",
    "module": "skiko",
    "version": "0.7.36-edit",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "skiko-metadata-0.7.36-edit-all.jar",
          "url": "skiko-0.7.36-edit-all.jar",
          "size": 647,
          "sha512": "693493dce813ff313ac62f3b54ddc85d6766ca14214c13b1e46305b321e4556b56a09b69ffe43962c57ce258703c43f9c4865fbd740c5bc26389884de6e1c0fe",
          "sha256": "87be0205fdf415219cb543f974bd16766f5f2c1f24e40636011c104281269951",
          "sha1": "88b9bfc383946048b34d75c8fe45e05d5e7775a7",
          "md5": "7f00abcefc4720f9f76e8ece83654bfd"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "skiko-0.7.36-edit.jar",
          "url": "skiko-0.7.36-edit.jar",
          "size": 191812,
          "sha512": "4c2573ec53212a9c16d72ba00c1eda3289700cdc88f0e9d8a16e68ed58ea05bebbc07d9d651fcd73aea7b6f63bf5da230a3bf99dc4249454e9c3cb7caeafe402",
          "sha256": "aa9510744a734622132591611598da84c43ce096e63aa7d96c3892ffc4239064",
          "sha1": "e9cf040d05d3bf633921ce3d9625b54a793f30a7",
          "md5": "e747e421c6e8bca26d43a358c7b3c89f"
        }
      ]
    },
    {
      "name": "awtApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../skiko-awt/0.7.36-edit/skiko-awt-0.7.36-edit.module",
        "group": "org.jetbrains.skiko",
        "module": "skiko-awt",
        "version": "0.7.36-edit"
      }
    },
    {
      "name": "awtRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../skiko-awt/0.7.36-edit/skiko-awt-0.7.36-edit.module",
        "group": "org.jetbrains.skiko",
        "module": "skiko-awt",
        "version": "0.7.36-edit"
      }
    }
  ]
}
