{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.skiko",
    "module": "skiko",
    "version": "0.7.36-edit",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "skiko-metadata-0.7.36-edit-all.jar",
          "url": "skiko-0.7.36-edit-all.jar",
          "size": 647,
          "sha512": "85b327564c8d1b1decaf2208035c5519200b4499b0308919de1ab5d5bec3248a46c263bb081a3aa9a71f700235f5b064956ea771b79a2a6b0bc83381963db4ef",
          "sha256": "0b6d1dce2edf81c455c8ccc344305c902bd3519315cae9815a895a41af35fe50",
          "sha1": "43cc9d64611a12873b37f2421d88ab7e20796b4d",
          "md5": "0ce718fc0e75bab47fb559394c90b521"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "skiko-0.7.36-edit.jar",
          "url": "skiko-0.7.36-edit.jar",
          "size": 191812,
          "sha512": "e39fb6226fc662f00ed6334d9036b39e608262b8ff08665e2b54a61b5899765a674a14ac5103db4f047244e0d83e6e485b4d61495d47d14fee81d53d887a71d0",
          "sha256": "e81f55100c77190669c365dda92fd905ab1cf344e515f41942fd483ac4127553",
          "sha1": "6c96dc8307c40d26c46ac23f71221d2ccdd6d57b",
          "md5": "d3b60ff95a42c491ff7d0be87760f4e9"
        }
      ]
    },
    {
      "name": "awtApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../skiko-awt/0.7.36-edit/skiko-awt-0.7.36-edit.module",
        "group": "org.jetbrains.skiko",
        "module": "skiko-awt",
        "version": "0.7.36-edit"
      }
    },
    {
      "name": "awtRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../skiko-awt/0.7.36-edit/skiko-awt-0.7.36-edit.module",
        "group": "org.jetbrains.skiko",
        "module": "skiko-awt",
        "version": "0.7.36-edit"
      }
    }
  ]
}
