{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.skiko",
    "module": "skiko",
    "version": "0.7.36-edit",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "skiko-metadata-0.7.36-edit-all.jar",
          "url": "skiko-0.7.36-edit-all.jar",
          "size": 647,
          "sha512": "87e73aa8e400554c6c6f1784487088b3a9d4d1aca783d6b5db720cf3882e32e9f72f1e1a1c6da688fec3e18756bdf1f467c645e5d05a1cc5904900e865b93d18",
          "sha256": "f2da62ea72104d2471ca1f25fb38a175cfa340888867a8b457138e24f7c1874e",
          "sha1": "d17177297e067124fa4de28526f5448ca0d0cc2a",
          "md5": "85c3104c88bf3ed42be913e75db0bb67"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "skiko-0.7.36-edit.jar",
          "url": "skiko-0.7.36-edit.jar",
          "size": 191812,
          "sha512": "97e8d6bb85796b8fac4720e4284ea70ede2fdc881f3d1b64abfe2f86d2d75765784f052571aab83bffa1f5b841700638763a4632c6b26d327470a03eda2426b8",
          "sha256": "bf768c4236238d407f9a947e945cdd2b98664b079058f550791aaeb80b69f8b7",
          "sha1": "b55dd724f2ca875ce6f8963f0e42d1c1649c80cd",
          "md5": "a2bc5373c5bd7fdb81b97dd32885f38a"
        }
      ]
    },
    {
      "name": "awtApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../skiko-awt/0.7.36-edit/skiko-awt-0.7.36-edit.module",
        "group": "org.jetbrains.skiko",
        "module": "skiko-awt",
        "version": "0.7.36-edit"
      }
    },
    {
      "name": "awtRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../skiko-awt/0.7.36-edit/skiko-awt-0.7.36-edit.module",
        "group": "org.jetbrains.skiko",
        "module": "skiko-awt",
        "version": "0.7.36-edit"
      }
    }
  ]
}
