{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.compose",
    "module": "preview-rpc",
    "version": "1.2.0-edit1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "preview-rpc-1.2.0-edit1.jar",
          "url": "preview-rpc-1.2.0-edit1.jar",
          "size": 126833,
          "sha512": "b85e47877073a7af006ec51867dd54ad2a27cb719f3f7f8a7566e18dd2317a01ece74a9b33822485626be1ef97299840b32a6cb37679328c0342d44ba03d7ec9",
          "sha256": "f12481b2773f8c1988cf508be747329eae581b25d72e3eb94d0393fce25c2f25",
          "sha1": "228796a19151208ca2c902d7b09cfe3b09302978",
          "md5": "1f9d2b5098e624447953f4bc88f354a7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "preview-rpc-1.2.0-edit1.jar",
          "url": "preview-rpc-1.2.0-edit1.jar",
          "size": 126833,
          "sha512": "b85e47877073a7af006ec51867dd54ad2a27cb719f3f7f8a7566e18dd2317a01ece74a9b33822485626be1ef97299840b32a6cb37679328c0342d44ba03d7ec9",
          "sha256": "f12481b2773f8c1988cf508be747329eae581b25d72e3eb94d0393fce25c2f25",
          "sha1": "228796a19151208ca2c902d7b09cfe3b09302978",
          "md5": "1f9d2b5098e624447953f4bc88f354a7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "preview-rpc-1.2.0-edit1-javadoc.jar",
          "url": "preview-rpc-1.2.0-edit1-javadoc.jar",
          "size": 261,
          "sha512": "661e5e0c176e8d8c8492af2cffde7ab091acf6acff316a2a608731a10d5ce0d02e2361d24fcec8df3b02ecabd849094e42b70d43114c5e767b8b4aa6ac014d98",
          "sha256": "106029b0bc1d80d2dc5b175b15fe280dd4497b0bb63ad7ab96c0428d63fe2b62",
          "sha1": "9cedd2529d37dffc5737eb6b1774faf00b01e574",
          "md5": "1282f6e2a88393cabf945a2f93e889da"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "preview-rpc-1.2.0-edit1-sources.jar",
          "url": "preview-rpc-1.2.0-edit1-sources.jar",
          "size": 17324,
          "sha512": "bc845043eea5cf8bbd094e01d9a8b93ebe3fd4f0131a984df414a7fe75fedb2a9b5bdddb91ca3d62bf8e32d5570b0941d139772e650371dbcec8a41dd7d0607a",
          "sha256": "29e635d2e8e5ef3a0bcf6423790e28c8cbed3d4820d89d9ac3c7caa2cd11c8d6",
          "sha1": "73b4311134ed1a98886f2c30d2f9366382d8b33b",
          "md5": "cc30762d3ac377f95d84775325c90876"
        }
      ]
    }
  ]
}
