{
  "formatVersion": "1.1",
  "component": {
    "group": "me.yuugiri.compose.compiler",
    "module": "compiler",
    "version": "1.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "compiler-1.3.3.jar",
          "url": "compiler-1.3.3.jar",
          "size": 955989,
          "sha512": "28130b8b10948bf8ab023dccb7bf35fa54b76c7808ad369364c5be388e1892ffa9abd08b9ca1150168f73a9367cd1a699ba46bf1c15fc68e10e913bae9ec2c57",
          "sha256": "558a8bf1fa7cb7cde76e78c0c76a21493ef2de8cf212b0b5c894c09c58ed4851",
          "sha1": "98ef4c3dd36151361097adaffa06840fe5779daa",
          "md5": "35262a75ee1cab3e4bedf21c754513ab"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compiler-1.3.3.jar",
          "url": "compiler-1.3.3.jar",
          "size": 955989,
          "sha512": "28130b8b10948bf8ab023dccb7bf35fa54b76c7808ad369364c5be388e1892ffa9abd08b9ca1150168f73a9367cd1a699ba46bf1c15fc68e10e913bae9ec2c57",
          "sha256": "558a8bf1fa7cb7cde76e78c0c76a21493ef2de8cf212b0b5c894c09c58ed4851",
          "sha1": "98ef4c3dd36151361097adaffa06840fe5779daa",
          "md5": "35262a75ee1cab3e4bedf21c754513ab"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compiler-1.3.3-sources.jar",
          "url": "compiler-1.3.3-sources.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}