{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.compose",
    "module": "preview-rpc",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "preview-rpc-1.2.0.jar",
          "url": "preview-rpc-1.2.0.jar",
          "size": 126833,
          "sha512": "ebbff2d006c2dd77c1840820c3d8792ddca4130dcbf749c7963c10293cfcf3db28bb803aaef267e54bdc7ad64d8c46e08b4afd235d16a43b73acd8d326d0b899",
          "sha256": "ebaa8ca88e203ad5aa9f1c742d66c3cb9758d35dbf5aab87f3d7805264029aae",
          "sha1": "395e8fd308d2439d54192fc8041411b930b3aaf1",
          "md5": "2ca02013e0cec42b6a19401517f47e6f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "preview-rpc-1.2.0.jar",
          "url": "preview-rpc-1.2.0.jar",
          "size": 126833,
          "sha512": "ebbff2d006c2dd77c1840820c3d8792ddca4130dcbf749c7963c10293cfcf3db28bb803aaef267e54bdc7ad64d8c46e08b4afd235d16a43b73acd8d326d0b899",
          "sha256": "ebaa8ca88e203ad5aa9f1c742d66c3cb9758d35dbf5aab87f3d7805264029aae",
          "sha1": "395e8fd308d2439d54192fc8041411b930b3aaf1",
          "md5": "2ca02013e0cec42b6a19401517f47e6f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "preview-rpc-1.2.0-javadoc.jar",
          "url": "preview-rpc-1.2.0-javadoc.jar",
          "size": 261,
          "sha512": "dd951ab1768dc75f4499950bbe2bc85b33ac32382dfcedb8b14aa1ee89516d5ba2e554eec32af0dfa9f4342d3d18c47602f5e55904b186bff7ade4dc7586403d",
          "sha256": "4e83db3c86436bb568c0e9c4c0fdb8a46882a9f7e1ee4aeaf04a691d193a972c",
          "sha1": "123700ebc92eaab341840110f4dde4627f7b6932",
          "md5": "b674fe041c6c95b9b9c41f38e53b5385"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "preview-rpc-1.2.0-sources.jar",
          "url": "preview-rpc-1.2.0-sources.jar",
          "size": 17324,
          "sha512": "ae8c21372bee9f5bbcb1c0e86b323726e38931f7350d95b4013e73e65daf6fe90548498cee192c6de8c1e13559efe4136faaedc0c83d14610bd4c23f334f93b9",
          "sha256": "d5c80b8682240ac9d88594d1a17051b11d94acf2171ba97c1ead42667fe05bfe",
          "sha1": "03d75897968e503feca708419ae10b4e7fad64e5",
          "md5": "818e83f85eb1c9683aad216433951630"
        }
      ]
    }
  ]
}
